// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: worker_execution.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Attempt       int32                  `protobuf:"varint,2,opt,name=attempt,proto3" json:"attempt,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,3,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_worker_execution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_execution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_worker_execution_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ExecuteRequest) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *ExecuteRequest) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ExecuteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SUCCESS | FAILED | DUPLICATE_SKIPPED
	Status           string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	DuplicateSkipped bool   `protobuf:"varint,2,opt,name=duplicate_skipped,json=duplicateSkipped,proto3" json:"duplicate_skipped,omitempty"`
	ErrorMessage     string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_worker_execution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_execution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_worker_execution_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteResponse) GetDuplicateSkipped() bool {
	if x != nil {
		return x.DuplicateSkipped
	}
	return false
}

func (x *ExecuteResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_worker_execution_proto protoreflect.FileDescriptor

const file_worker_execution_proto_rawDesc = "" +
	"\n" +
	"\x16worker_execution.proto\x12\x11kernelq.worker.v1\"\xc7\x01\n" +
	"\x0eExecuteRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x18\n" +
	"\aattempt\x18\x02 \x01(\x05R\aattempt\x12H\n" +
	"\apayload\x18\x03 \x03(\v2..kernelq.worker.v1.ExecuteRequest.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"{\n" +
	"\x0fExecuteResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12+\n" +
	"\x11duplicate_skipped\x18\x02 \x01(\bR\x10duplicateSkipped\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage2j\n" +
	"\x16WorkerExecutionService\x12P\n" +
	"\aExecute\x12!.kernelq.worker.v1.ExecuteRequest\x1a\".kernelq.worker.v1.ExecuteResponseBGZEgithub.com/KushalGautamKG/workos-scheduler/worker/internal/grpc/pb;pbb\x06proto3"

var (
	file_worker_execution_proto_rawDescOnce sync.Once
	file_worker_execution_proto_rawDescData []byte
)

func file_worker_execution_proto_rawDescGZIP() []byte {
	file_worker_execution_proto_rawDescOnce.Do(func() {
		file_worker_execution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_execution_proto_rawDesc), len(file_worker_execution_proto_rawDesc)))
	})
	return file_worker_execution_proto_rawDescData
}

var file_worker_execution_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_worker_execution_proto_goTypes = []any{
	(*ExecuteRequest)(nil),  // 0: kernelq.worker.v1.ExecuteRequest
	(*ExecuteResponse)(nil), // 1: kernelq.worker.v1.ExecuteResponse
	nil,                     // 2: kernelq.worker.v1.ExecuteRequest.PayloadEntry
}
var file_worker_execution_proto_depIdxs = []int32{
	2, // 0: kernelq.worker.v1.ExecuteRequest.payload:type_name -> kernelq.worker.v1.ExecuteRequest.PayloadEntry
	0, // 1: kernelq.worker.v1.WorkerExecutionService.Execute:input_type -> kernelq.worker.v1.ExecuteRequest
	1, // 2: kernelq.worker.v1.WorkerExecutionService.Execute:output_type -> kernelq.worker.v1.ExecuteResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_worker_execution_proto_init() }
func file_worker_execution_proto_init() {
	if File_worker_execution_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_execution_proto_rawDesc), len(file_worker_execution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_execution_proto_goTypes,
		DependencyIndexes: file_worker_execution_proto_depIdxs,
		MessageInfos:      file_worker_execution_proto_msgTypes,
	}.Build()
	File_worker_execution_proto = out.File
	file_worker_execution_proto_goTypes = nil
	file_worker_execution_proto_depIdxs = nil
}
