// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: worker_execution.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkerExecutionService_Execute_FullMethodName = "/kernelq.worker.v1.WorkerExecutionService/Execute"
)

// WorkerExecutionServiceClient is the client API for WorkerExecutionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkerExecutionService is the internal execution RPC boundary.
// Day 116: contract + local Go skeleton only — Kafka dispatch path unchanged.
type WorkerExecutionServiceClient interface {
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error)
}

type workerExecutionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkerExecutionServiceClient(cc grpc.ClientConnInterface) WorkerExecutionServiceClient {
	return &workerExecutionServiceClient{cc}
}

func (c *workerExecutionServiceClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (*ExecuteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteResponse)
	err := c.cc.Invoke(ctx, WorkerExecutionService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkerExecutionServiceServer is the server API for WorkerExecutionService service.
// All implementations must embed UnimplementedWorkerExecutionServiceServer
// for forward compatibility.
//
// WorkerExecutionService is the internal execution RPC boundary.
// Day 116: contract + local Go skeleton only — Kafka dispatch path unchanged.
type WorkerExecutionServiceServer interface {
	Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error)
	mustEmbedUnimplementedWorkerExecutionServiceServer()
}

// UnimplementedWorkerExecutionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkerExecutionServiceServer struct{}

func (UnimplementedWorkerExecutionServiceServer) Execute(context.Context, *ExecuteRequest) (*ExecuteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedWorkerExecutionServiceServer) mustEmbedUnimplementedWorkerExecutionServiceServer() {
}
func (UnimplementedWorkerExecutionServiceServer) testEmbeddedByValue() {}

// UnsafeWorkerExecutionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkerExecutionServiceServer will
// result in compilation errors.
type UnsafeWorkerExecutionServiceServer interface {
	mustEmbedUnimplementedWorkerExecutionServiceServer()
}

func RegisterWorkerExecutionServiceServer(s grpc.ServiceRegistrar, srv WorkerExecutionServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkerExecutionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkerExecutionService_ServiceDesc, srv)
}

func _WorkerExecutionService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkerExecutionServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkerExecutionService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkerExecutionServiceServer).Execute(ctx, req.(*ExecuteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkerExecutionService_ServiceDesc is the grpc.ServiceDesc for WorkerExecutionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkerExecutionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kernelq.worker.v1.WorkerExecutionService",
	HandlerType: (*WorkerExecutionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _WorkerExecutionService_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "worker_execution.proto",
}
